/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserAccountService } from "../userAccount.service";
import { UserAccountCreateInput } from "./UserAccountCreateInput";
import { UserAccount } from "./UserAccount";
import { UserAccountFindManyArgs } from "./UserAccountFindManyArgs";
import { UserAccountWhereUniqueInput } from "./UserAccountWhereUniqueInput";
import { UserAccountUpdateInput } from "./UserAccountUpdateInput";
import { ControllerInputFindManyArgs } from "../../controllerInput/base/ControllerInputFindManyArgs";
import { ControllerInput } from "../../controllerInput/base/ControllerInput";
import { ControllerInputWhereUniqueInput } from "../../controllerInput/base/ControllerInputWhereUniqueInput";

export class UserAccountControllerBase {
  constructor(protected readonly service: UserAccountService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserAccount })
  async createUserAccount(
    @common.Body() data: UserAccountCreateInput
  ): Promise<UserAccount> {
    return await this.service.createUserAccount({
      data: data,
      select: {
        createdAt: true,
        hat: true,
        height: true,
        id: true,
        pants: true,
        shirt: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserAccount] })
  @ApiNestedQuery(UserAccountFindManyArgs)
  async userAccounts(@common.Req() request: Request): Promise<UserAccount[]> {
    const args = plainToClass(UserAccountFindManyArgs, request.query);
    return this.service.userAccounts({
      ...args,
      select: {
        createdAt: true,
        hat: true,
        height: true,
        id: true,
        pants: true,
        shirt: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userAccount(
    @common.Param() params: UserAccountWhereUniqueInput
  ): Promise<UserAccount | null> {
    const result = await this.service.userAccount({
      where: params,
      select: {
        createdAt: true,
        hat: true,
        height: true,
        id: true,
        pants: true,
        shirt: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserAccount(
    @common.Param() params: UserAccountWhereUniqueInput,
    @common.Body() data: UserAccountUpdateInput
  ): Promise<UserAccount | null> {
    try {
      return await this.service.updateUserAccount({
        where: params,
        data: data,
        select: {
          createdAt: true,
          hat: true,
          height: true,
          id: true,
          pants: true,
          shirt: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserAccount(
    @common.Param() params: UserAccountWhereUniqueInput
  ): Promise<UserAccount | null> {
    try {
      return await this.service.deleteUserAccount({
        where: params,
        select: {
          createdAt: true,
          hat: true,
          height: true,
          id: true,
          pants: true,
          shirt: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/controllerInputs")
  @ApiNestedQuery(ControllerInputFindManyArgs)
  async findControllerInputs(
    @common.Req() request: Request,
    @common.Param() params: UserAccountWhereUniqueInput
  ): Promise<ControllerInput[]> {
    const query = plainToClass(ControllerInputFindManyArgs, request.query);
    const results = await this.service.findControllerInputs(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        inputType: true,
        inputValue: true,
        timestamp: true,
        updatedAt: true,

        userAccount: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/controllerInputs")
  async connectControllerInputs(
    @common.Param() params: UserAccountWhereUniqueInput,
    @common.Body() body: ControllerInputWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      controllerInputs: {
        connect: body,
      },
    };
    await this.service.updateUserAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/controllerInputs")
  async updateControllerInputs(
    @common.Param() params: UserAccountWhereUniqueInput,
    @common.Body() body: ControllerInputWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      controllerInputs: {
        set: body,
      },
    };
    await this.service.updateUserAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/controllerInputs")
  async disconnectControllerInputs(
    @common.Param() params: UserAccountWhereUniqueInput,
    @common.Body() body: ControllerInputWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      controllerInputs: {
        disconnect: body,
      },
    };
    await this.service.updateUserAccount({
      where: params,
      data,
      select: { id: true },
    });
  }
}
